train:
  - HorizontalFlip:
      p: 0.5

  - ShiftScaleRotate:
      shift_limit: 0.05
      scale_limit: 0.2
      rotate_limit: 10
      border_mode: 0
      p: 0.5

  - ColorJitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.05
      p: 0.7

  - HueSaturationValue:
      hue_shift_limit: 10
      sat_shift_limit: 20
      val_shift_limit: 10
      p: 0.5

  - RandomBrightnessContrast:
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5

  - CLAHE:
      clip_limit: 2.0
      tile_grid_size: [8, 8]
      p: 0.3

  - GaussianBlur:
      blur_limit: 3
      p: 0.2

  - MotionBlur:
      blur_limit: 5
      p: 0.2

val: []
