train:
  - HorizontalFlip:
      p: 0.5

  - RandomBrightnessContrast:
      brightness_limit: 0.1
      contrast_limit: 0.1
      p: 0.3

  - HueSaturationValue:
      hue_shift_limit: 5
      sat_shift_limit: 10
      val_shift_limit: 5
      p: 0.3

val: []
