train:
  - HorizontalFlip:
      p: 0.5

  - ShiftScaleRotate:
      shift_limit: 0.05
      scale_limit: 0.15
      rotate_limit: 10
      border_mode: 0
      p: 0.5

  - ColorJitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.05
      p: 0.6

  - RandomBrightnessContrast:
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5

  - GaussianBlur:
      blur_limit: 3
      p: 0.2

val: []
