train:
  - HorizontalFlip:
      p: 0.5

  - ShiftScaleRotate:
      shift_limit: 0.1
      scale_limit: 0.3
      rotate_limit: 15
      border_mode: 0
      p: 0.7

  - ColorJitter:
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.1
      p: 0.8

  - HueSaturationValue:
      hue_shift_limit: 15
      sat_shift_limit: 30
      val_shift_limit: 15
      p: 0.7

  - RandomBrightnessContrast:
      brightness_limit: 0.3
      contrast_limit: 0.3
      p: 0.6

  - MotionBlur:
      blur_limit: 7
      p: 0.3

  - GaussNoise:
      var_limit: [10.0, 50.0]
      p: 0.3

  - CLAHE:
      clip_limit: 2.0
      tile_grid_size: [8, 8]
      p: 0.4

val: []
